language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-20.0

before_script:
    - cp keystore.properties.example keystore.properties
    - cp readability.properties.example readability.properties
    - cp local.properties.example local.properties

script: ./gradlew clean assembleTravis
